development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: pguser
  password: 1234
  database: sinatra_test
  schema_search_path: public
  encoding: utf8
  template: template1

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: pguser
  password: 1234
  database: sinatra_test
  schema_search_path: public
  encoding: utf8
  template: template1
